spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/training?serverTimezone=UTC
    username: root
    password: 123456

#  mvc:
#    path match:
#      matching-strategy: ant_path_matcher
#  main:
#    allow-circular-references: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081